default_language_version:
  python: python3
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: detect-private-key
    id: trailing-whitespace
    stages: [pre-commit]
- repo: https://github.com/codespell-project/codespell
  rev: v2.1.0
  hooks:
  - id: codespell
    exclude: COMMIT_EDITMSG
    stages: [pre-commit]
- repo: https://github.com/Yelp/detect-secrets
  rev: v1.1.0
  hooks:
  - id: detect-secrets
    stages: [pre-commit]
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v14.0.6
  hooks:
  - id: clang-format