#pragma once

#include <optional>
#include <queue>
#include <array>
#include "common.h"
#include "interrupts.h"

namespace CPUE {


/**
 * Programmable Interrupt Controller
 *
 * NOTE: WE CURRENTLY DON'T SUPPORT PIC
 *
 *
 * Is only responsible for interrupts generated by external devices such as
 *  - watchdog timers (although some watchdogs can also use the NMI pin and bypass the PIC)
 *  - keyboards
 *  - hard drives
 *  - etc.
 *
 *
 * PICs typically have a common set of registers:
 *  - interrupt request register (IRR),
 *  - in-service register (ISR),
 *  - and interrupt mask register (IMR).
 * The IRR specifies which interrupts are pending acknowledgement.
 * The ISR register specifies which interrupts have been acknowledged, but are still waiting for an end of interrupt (EOI).
 * The IMR specifies which interrupts are to be ignored and not acknowledged.
 * A simple register schema such as this allows up to two distinct interrupt requests to be outstanding at one time,
 * one waiting for acknowledgement, and one waiting for EOI.
 *
 * NOTE: The masking functionality is integrated into the interrupt controller, so masked interrupts do not reach the CPU at all.
 *
 * NOTE: By design PIC won't raise another interrupt until the CPU acknowledged the current interrupt.
 *
 * NOTE:
 * Once the interrupt is acknowledged by the CPU the interrupt controller can request another interrupt,
 * regardless if the CPU finished handled the previous interrupt or not.
 * Thus, depending on how the OS controls the CPU it is possible to have nested interrupts.
 *
 * When a device connected to one of the PIC's IRQ lines needs CPU attention the following flow happens:
 * 1. When the PIC receives an unmasked interrupt from a device (PIC interrupts
 *    are edge-triggered with high pin polarity), it sets the corresponding bit in its
 *    IRR (interrupt request register)
 * 2. The IRQ is dispatched to the CPU
 *    2.1 PIC converts the IRQ into a vector number and writes it to a port for CPU to read
 *    2.2 PIC raises an interrupt on CPU INTR pin
 *    2.3 PIC waits for CPU to acknowledge an interrupt before raising another interrupt
 * 3. The CPU acknowledges the IRQ.
 * 4. The PIC sets the corresponding bit in its ISR (in-service register) and clears the
 *    previously set bit in the IRR. If the same interrupt occurs again, it can now
 *    be queued a single time in the IRR.
 * 5. When the interrupt is being handled by the OS, it sends an EOI to the PIC,
 *    which clears the corresponding bit in the ISR
 *
 * When an interrupt is acknowledged the highest priority request is determined and its vector placed on
 * the bus. Additionally, a bit of the Interrupt Service register (ISO-7) is set. This bit remains set until the
 * microprocessor issues an End of Interrupt (EOI) command immediately before returning from the
 * service routine, or if AEOI (Automatic End of Interrupt) bit is set, until the trailing edge of the last INTA.
 *
 * To signal that an interrupt is being handled by the software, the interrupt controller receives an EOI (end of interrupt) notice from the OS.
 *
 * Most architectures also support interrupt priorities. When this is enabled,
 * it permits interrupt nesting only for those interrupts that have a higher priority than the current priority level.
 *
 */



class PIC {
public:
    PIC() = default;
    PIC(PIC const&) = delete;
};

}